data_dir: "TU-berlin-dataset/"

model: "resnet50"

train_batch_size: 20
val_batch_size: 20
test_batch_size: 1

warm_up_epochs: 10

num_epochs: 50

lr: 0.0001
optimizer: Adam

center_loss_lr: 0.00005


lr_patience: 8
lr_decay_factor: 0.5

weight_decay: 0.0001
seed: 42
loss_function: "ContrastiveCenter"

unfreeze: last_three_blocks

invert_colors: False
num_workers: 4
pretrained: False

# hidden_dim: 1024
num_classes: 250

best_ckpt_path: "new_saved_models/seed_42/res50_best_scratch"
ckpt_path: "new_saved_models/seed_42/res50_scratch"