train_images_list_file: image_splits_files/train/data_2024_10_04_m12_train_list_split_3.txt
val_images_list_file: image_splits_files/val/data_2024_10_04_m12_validation_list_split_3.txt

size: 512

augmentations: 

target: regression

target_task: MOCA_0_18_TO_12_18

train_batch_size: 6
val_batch_size: 6

num_workers: 4

lr: 0.0001
num_epochs: 50

optimizer: Adam
weight_decay: 0.0001

num_classes: 1

model: resnet101
warm_up_epochs: 10

lr_patience: 8
lr_decay_factor: 0.5

loss_function: L1
unfreeze: last_three_blocks
pretrained: False

best_ckpt: alz_saved_models/Res101_TuPretrained_sc_regression_0_to_12_3.pth
tu_berlin_ckpt: new_saved_models/seed_42/res101_best_scratch_fold0.pth